version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: sejahteraku-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rahasia
      - POSTGRES_DB=sejahteraku_db
    ports:
      - "5434:5432"